apiVersion: 1

datasources:
  - name: SupplyChainDB
    type: postgres
    uid: supply_chain_pg
    url: postgres:5432
    user: supplychain
    secureJsonData:
      password: supplychain_secret
    jsonData:
      database: supply_chain_db
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: false
